// ============================================================
// Central endpoint registry. "Controller/Action" relative to the
// /api/v1 base URL (see axiosInstance.APIBaseURL). Grouped by controller,
// matching the hospediav12-fe apiEndpoints.js format.
// ============================================================
export const apiUrls = {
  // ---------- Clients ----------
  GetClientList: "Clients/GetClientList",
  GetClientById: "Clients/GetClientById",
  GetClientProjects: "Clients/GetClientProjects",
  InsertClient: "Clients/InsertClient",
  UpdateClient: "Clients/UpdateClient",
  DeleteClient: "Clients/DeleteClient",

  // ---------- Projects ----------
  GetProjectList: "Projects/GetProjectList",
  GetProjectByCode: "Projects/GetProjectByCode",
  InsertProject: "Projects/InsertProject",
  UpdateProject: "Projects/UpdateProject",
  DeleteProject: "Projects/DeleteProject",
  SetOnboardingStep: "Projects/SetOnboardingStep",
  GetProjectModules: "Projects/GetProjectModules",
  SaveProjectModules: "Projects/SaveProjectModules",
  GetProjectInterfaces: "Projects/GetProjectInterfaces",
  SaveProjectInterfaces: "Projects/SaveProjectInterfaces",
  GetProjectMilestones: "Projects/GetProjectMilestones",

  // ---------- Team ----------
  GetTeamMemberList: "Team/GetTeamMemberList",
  GetTeamMemberById: "Team/GetTeamMemberById",
  InsertTeamMember: "Team/InsertTeamMember",
  UpdateTeamMember: "Team/UpdateTeamMember",
  DeleteTeamMember: "Team/DeleteTeamMember",

  // ---------- Delivery (SRS, requirements, master data, dev, UAT, bugs, training, go-live) ----------
  GetSrsSessionList: "Delivery/GetSrsSessionList",
  InsertSrsSession: "Delivery/InsertSrsSession",
  UpdateSrsSession: "Delivery/UpdateSrsSession",
  DeleteSrsSession: "Delivery/DeleteSrsSession",
  GetRequirementList: "Delivery/GetRequirementList",
  InsertRequirement: "Delivery/InsertRequirement",
  UpdateRequirement: "Delivery/UpdateRequirement",
  DeleteRequirement: "Delivery/DeleteRequirement",
  GetMasterDataRecordList: "Delivery/GetMasterDataRecordList",
  InsertMasterDataRecord: "Delivery/InsertMasterDataRecord",
  UpdateMasterDataRecord: "Delivery/UpdateMasterDataRecord",
  DeleteMasterDataRecord: "Delivery/DeleteMasterDataRecord",
  GetDevelopmentItemList: "Delivery/GetDevelopmentItemList",
  InsertDevelopmentItem: "Delivery/InsertDevelopmentItem",
  UpdateDevelopmentItem: "Delivery/UpdateDevelopmentItem",
  DeleteDevelopmentItem: "Delivery/DeleteDevelopmentItem",
  GetUatCaseList: "Delivery/GetUatCaseList",
  InsertUatCase: "Delivery/InsertUatCase",
  UpdateUatCase: "Delivery/UpdateUatCase",
  DeleteUatCase: "Delivery/DeleteUatCase",
  GetBugList: "Delivery/GetBugList",
  InsertBug: "Delivery/InsertBug",
  UpdateBug: "Delivery/UpdateBug",
  DeleteBug: "Delivery/DeleteBug",
  GetTrainingList: "Delivery/GetTrainingList",
  InsertTraining: "Delivery/InsertTraining",
  UpdateTraining: "Delivery/UpdateTraining",
  DeleteTraining: "Delivery/DeleteTraining",
  GetGoLiveReadinessList: "Delivery/GetGoliveReadinessList",
  GetLiveImportList: "Delivery/GetLiveImportList",
  GetParallelGoLiveList: "Delivery/GetParallelGoliveList",
  GetFinalGoLiveList: "Delivery/GetFinalGoliveList",

  // ---------- Governance ----------
  GetIssueList: "Governance/GetIssueList",
  InsertIssue: "Governance/InsertIssue",
  UpdateIssue: "Governance/UpdateIssue",
  DeleteIssue: "Governance/DeleteIssue",
  GetRiskList: "Governance/GetRiskList",
  InsertRisk: "Governance/InsertRisk",
  UpdateRisk: "Governance/UpdateRisk",
  DeleteRisk: "Governance/DeleteRisk",
  GetSignoffList: "Governance/GetSignoffList",
  InsertSignoff: "Governance/InsertSignoff",
  UpdateSignoff: "Governance/UpdateSignoff",
  DeleteSignoff: "Governance/DeleteSignoff",
  GetDocumentList: "Governance/GetDocumentList",
  InsertDocument: "Governance/InsertDocument",
  UpdateDocument: "Governance/UpdateDocument",
  DeleteDocument: "Governance/DeleteDocument",

  // ---------- Activities & hospital users ----------
  GetActivityList: "Activities/GetActivityList",
  GetActivityById: "Activities/GetActivityById",
  InsertActivity: "Activities/InsertActivity",
  UpdateActivity: "Activities/UpdateActivity",
  DeleteActivity: "Activities/DeleteActivity",
  GetActivityModules: "Activities/GetActivityModules",
  SaveActivityModules: "Activities/SaveActivityModules",
  GetHospitalUserList: "Activities/GetHospitalUserList",
  InsertHospitalUser: "Activities/InsertHospitalUser",
  UpdateHospitalUser: "Activities/UpdateHospitalUser",
  DeleteHospitalUser: "Activities/DeleteHospitalUser",

  // ---------- Integrations (SIR) ----------
  GetIntegrationList: "Integrations/GetIntegrationList",
  GetIntegrationById: "Integrations/GetIntegrationById",
  GetIntegrationApis: "Integrations/GetIntegrationApis",
  InsertIntegration: "Integrations/InsertIntegration",
  UpdateIntegration: "Integrations/UpdateIntegration",
  DeleteIntegration: "Integrations/DeleteIntegration",
  GetProcessFlowList: "Integrations/GetProcessFlowList",
  GetHimsChangeList: "Integrations/GetHimsChangeList",
  GetDbChangeList: "Integrations/GetDbChangeList",
  GetSourceCodeList: "Integrations/GetSourceCodeList",
  GetIntegrationScreenList: "Integrations/GetIntegrationScreenList",
  GetClientImplementationList: "Integrations/GetClientImplementationList",
  GetIntegrationTestCaseList: "Integrations/GetIntegrationTestCaseList",
  GetIntegrationDocumentList: "Integrations/GetIntegrationDocumentList",
  GetVersionHistoryList: "Integrations/GetVersionHistoryList",
  GetDeveloperNoteList: "Integrations/GetDeveloperNoteList",
  GetVendorList: "Integrations/GetVendorList",

  // ---------- APIs & payloads ----------
  GetApiList: "Apis/GetApiList",
  GetApiById: "Apis/GetApiById",
  InsertApi: "Apis/InsertApi",
  UpdateApi: "Apis/UpdateApi",
  DeleteApi: "Apis/DeleteApi",
  SaveApiPayload: "Apis/SaveApiPayload",
  GetApiPayloadList: "Apis/GetApiPayloadList",

  // ---------- Features (SFR) ----------
  GetFeatureList: "Features/GetFeatureList",
  GetFeatureById: "Features/GetFeatureById",
  InsertFeature: "Features/InsertFeature",
  UpdateFeature: "Features/UpdateFeature",
  DeleteFeature: "Features/DeleteFeature",
  AdvanceFeature: "Features/AdvanceFeature",
  SetFeatureStatus: "Features/SetFeatureStatus",
  GetFeatureSegments: "Features/GetFeatureSegments",
  SaveFeatureSegments: "Features/SaveFeatureSegments",

  // ---------- Feature documentation ----------
  SaveBusinessAnalysis: "FeatureDocs/SaveBusinessAnalysis",
  SaveTechnicalAnalysis: "FeatureDocs/SaveTechnicalAnalysis",
  SaveWorkflow: "FeatureDocs/SaveWorkflow",
  SaveDevDetails: "FeatureDocs/SaveDevDetails",
  SaveImpact: "FeatureDocs/SaveImpact",
  GetFeatureBusinessAnalysisList: "FeatureDocs/GetFeatureBusinessAnalysisList",
  GetFeatureTechnicalAnalysisList: "FeatureDocs/GetFeatureTechnicalAnalysisList",
  GetFeatureWorkflowList: "FeatureDocs/GetFeatureWorkflowList",
  GetFeatureDevDetailsList: "FeatureDocs/GetFeatureDevDetailsList",
  GetFeatureImpactList: "FeatureDocs/GetFeatureImpactList",
  GetFeatureScreenChangeList: "FeatureDocs/GetFeatureScreenChangeList",
  GetFeatureTestList: "FeatureDocs/GetFeatureTestList",
  GetFeatureClientAdoptionList: "FeatureDocs/GetFeatureClientAdoptionList",
  GetFeatureKbDocList: "FeatureDocs/GetFeatureKbDocList",
  GetFeatureApprovalList: "FeatureDocs/GetFeatureApprovalList",

  // ---------- Dashboard ----------
  GetDashboardSummary: "Dashboard/GetDashboardSummary",
  GetNotificationList: "Dashboard/GetNotificationList",
  GetActivityFeedList: "Dashboard/GetActivityFeedList",
  GetUpcomingEventList: "Dashboard/GetUpcomingEventList",

  // ---------- Sfr analytics ----------
  GetSfrKpis: "Sfr/GetSfrKpis",
  GetFeatureCategoryMix: "Sfr/GetFeatureCategoryMix",

  // ---------- Lookups ----------
  GetCurrencyList: "Lookups/GetCurrencyList",
  GetCountryList: "Lookups/GetCountryList",
  GetSeverityLevelList: "Lookups/GetSeverityLevelList",
  GetHealthStatusList: "Lookups/GetHealthStatusList",
  GetProjectStatusList: "Lookups/GetProjectStatusList",
  GetProjectCategoryList: "Lookups/GetProjectCategoryList",
  GetImplementationTypeList: "Lookups/GetImplementationTypeList",
  GetHospitalTypeList: "Lookups/GetHospitalTypeList",
  GetProjectIntegrationTypeList: "Lookups/GetProjectIntegrationTypeList",
  GetLifecycleStageList: "Lookups/GetLifecycleStageList",
  GetHimsModuleList: "Lookups/GetHimsModuleList",
  GetHospitalDepartmentList: "Lookups/GetHospitalDepartmentList",
  GetInterfaceList: "Lookups/GetInterfaceList",
  GetRoleList: "Lookups/GetRoleList",
  GetTeamDepartmentList: "Lookups/GetTeamDepartmentList",
  GetIssueTypeList: "Lookups/GetIssueTypeList",
  GetRiskTypeList: "Lookups/GetRiskTypeList",
  GetTrainingTypeList: "Lookups/GetTrainingTypeList",
  GetDocCategoryList: "Lookups/GetDocCategoryList",
  GetSignoffMilestoneList: "Lookups/GetSignoffMilestoneList",
  GetBugCategoryList: "Lookups/GetBugCategoryList",
  GetIntegrationCategoryList: "Lookups/GetIntegrationCategoryList",
  GetIntegrationStatusList: "Lookups/GetIntegrationStatusList",
  GetHttpMethodList: "Lookups/GetHttpMethodList",
  GetAuthTypeList: "Lookups/GetAuthTypeList",
  GetFeatureModuleList: "Lookups/GetFeatureModuleList",
  GetFeatureCategoryList: "Lookups/GetFeatureCategoryList",
  GetFeatureStatusList: "Lookups/GetFeatureStatusList",
  GetApplicableSegmentList: "Lookups/GetApplicableSegmentList",
  GetKbDocTypeList: "Lookups/GetKbDocTypeList",
};
